graph TD;
	__start__([<p>__start__</p>]):::first
	Agent_TaskClassification(Agent_TaskClassification)
	Retriever(Retriever)
	Checking_Hop(Checking_Hop)
	Generator(Generator)
	__end__([<p>__end__</p>]):::last
	Agent_TaskClassification --> Retriever;
	Checking_Hop -. &nbsp;score >= 80&nbsp; .-> Generator;
	Checking_Hop -. &nbsp;score < 80&nbsp; .-> Retriever;
	Retriever --> Checking_Hop;
	__start__ --> Agent_TaskClassification;
	Generator --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc